apiVersion: v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: api
    image: api
    ports:
    - containerPort: 80
    - name: main
      image: main
    - name: log
      image: log
      volumeMounts:
      - name: log-storare
    - name: compute
      image: compute
      volumeMounts:
      - name: data-storage
