apiVersion: v1
kind: Pod
metadata:
  name: javaweb-2
spac:
  initContainers:
  - image: resouer/sample:v2
    name: war
    command: ['cp','/sample.war','/app']
    volumeMounts:
    - mountPrth: /app
      name: app-volume
  containers:
  - image: resouer/tomcat:7.0  
    name: tomcat
    command: ['sh','-c','/root/apache-tomcat-7.0.42-v2/bin/start.sh']
    volumeMounts:
    - mountPrth:
      name: app-volume
    ports:
    - containerPort: 8080
      hostPort: 8001
  volumes:
  - name: app-volume
    emptyDir: {}  

